FROM alt:p11

RUN apt-get update && \
    apt-get install -y curl unzip make gcc clang git

RUN mkdir -p /svace && \
    cd /svace && \
    curl -LJ -o svace-3.4.240516-x64-linux.tar.bz2 'https://nextcloud.ispras.ru/index.php/s/jjqs8iyCjNTQ2Xq/download?path=%2FSvace&files=svace-3.4.240516-x64-linux.tar.bz2' && \
    tar -xjvf svace-3.4.240516-x64-linux.tar.bz2 && \
    rm -rf svace-3.4.240516-x64-linux.tar.bz2 && \
    ln -s /svace/svace-3.4.240516-x64-linux/bin/svace /usr/local/bin/svace
